import { State } from "@/types/interfaces";

const mockedState = {
  user: {
    id: "",
    username: "Pablo",
    password: "",
    email: "",
    firstname: "",
    lastname: "",
    adminAccess: false,
    professorAccess: false,
    studentAccess: false,
    groups: [],
    studentErrors: [],
    image: "",
  },
  userId: "",
  token: "",
  refreshToken: "",
  isLoggedIn: false,
  isAdmin: false,
  isProfessor: false,
  isStudent: false,
  currentUser: {
    id: "1234567",
    username: "Pablo",
    password: "",
    email: "pablo@gmail.com",
    firstname: "Pablo",
    lastname: "Lopez",
    adminAccess: false,
    professorAccess: true,
    studentAccess: false,
    groups: [],
    studentErrors: [],
    image: "",
  },
  // eslint-disable-next-line no-unneeded-ternary
  isUserAuthenticated: localStorage.getItem("userData") ? true : false,
  prices: [],
  teachers: [],
  groups: [],
  userGroups: [],
  currentGroup: {},
  loadedUsersFromGroup: [],
  currentStudentErrors: [],
  loadedOneUserById: {},
};
export default mockedState as unknown as State;
